# Generated by Django 5.0.8 on 2024-08-27 10:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_url', models.URLField(help_text='Add slack url for get notification', max_length=2000)),
                ('web_url', models.URLField(help_text='Add Website url for monitoring', max_length=2000)),
                ('url_text', models.CharField(default='Site Link', help_text='Text to link web url', max_length=255)),
                ('text', models.CharField(help_text='Text for match in web site', max_length=200)),
                ('frequency', models.DurationField(default=datetime.timedelta(seconds=60), help_text='Set the time interval for the task')),
                ('name', models.ForeignKey(help_text='Name of user who added monitoring service.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
