# Generated by Django 5.0.8 on 2024-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sitechecker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitechecker',
            name='status',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
